import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import { CoffeeStore } from '../types';

import Banner from '../components/banner';
import Card from '../components/card';

import COFFEE_STORES from '../data/coffee-stores.json';

import styles from '../styles/Home.module.css';

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {
      coffeeStores: COFFEE_STORES,
    },
  };
};

type HomeProps = {
  coffeeStores: CoffeeStore[];
};

const Home: NextPage<HomeProps> = ({ coffeeStores }) => {
  const handleOnBannerBtnClick = () => {
    console.log('banner btn clicked');
  };

  return (
    <div>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero image"
          />
        </div>
        {coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.id}
                  name={coffeeStore.name}
                  imgUrl={coffeeStore.imgUrl}
                  href={`/coffee-store/${coffeeStore.id}`}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
